In [1]:
#Imports required
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

In [15]:
# reshaping
x = torch.rand(3,5) #first parameter = dimensions, second parameter = elements
print(x)
y = x.view(-1,3)
print(y)

tensor([[0.4160, 0.1326, 0.2982, 0.7058, 0.8730],
        [0.7834, 0.4607, 0.4110, 0.7813, 0.3256],
        [0.1527, 0.0740, 0.2917, 0.6323, 0.1302]])
tensor([[0.4160, 0.1326, 0.2982],
        [0.7058, 0.8730, 0.7834],
        [0.4607, 0.4110, 0.7813],
        [0.3256, 0.1527, 0.0740],
        [0.2917, 0.6323, 0.1302]])


In [17]:
# torch to numpy conversion
x = torch.rand(2,3)
print(x)
y = x.numpy()
print(y)

tensor([[0.3985, 0.9599, 0.4980],
        [0.5639, 0.9633, 0.1594]])
[[0.39845496 0.9599464  0.4980412 ]
 [0.56393224 0.96331006 0.15941775]]


In [35]:
# numpy to torch conversion
x = np.random.rand(2,3)
print(x)
y = torch.from_numpy(x).view(-1)
print(y)

[[0.84296866 0.55615392 0.83243546]
 [0.63694605 0.9632255  0.56368608]]
tensor([0.8430, 0.5562, 0.8324, 0.6369, 0.9632, 0.5637], dtype=torch.float64)
tensor([1.8430, 1.5562, 1.8324, 1.6369, 1.9632, 1.5637], dtype=torch.float64)
